# Generated by Django 3.1 on 2021-03-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kgustaCollege', '0002_remove_departments_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название отделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Абитуриентам',
                'verbose_name_plural': 'Абитуриентам',
            },
        ),
    ]
